/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Utils.SessionHelper;
import DAO.AdminDAO;
import Model.LogData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import Register.LoginPage;


/**
 *
 * @author ASUS
 */
public class LogPeminjaman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogPeminjaman.class.getName());

    /**
     * Creates new form LogPeminjaman
     */
    public LogPeminjaman() {
        if (!SessionHelper.checkAdmin(this)) return;
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        loadLogData(); // Panggil fungsi load saat dibuka
    }

    private void loadLogData() {
        AdminDAO dao = new AdminDAO();
        List<LogData> logs = dao.getLogPeminjaman();
        
        panelLogContainer.removeAll();
       
        panelLogContainer.setLayout(new GridLayout(0, 1, 0, 5));
        
        int no = 1;
        for (LogData log : logs){
            JPanel row = createLogRow(no++, log);
            panelLogContainer.add(row);
        }
        
        panelLogContainer.revalidate();
        panelLogContainer.repaint();
    }

    private javax.swing.JPanel createLogRow(int nomor, Model.LogData log) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(null);

        panel.setPreferredSize(new java.awt.Dimension(800, 50)); 
        panel.setBackground(java.awt.Color.WHITE);
       
        panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(220, 220, 220)));

        // Helper Font
        java.awt.Font fontIsi = new java.awt.Font("Segoe UI", 0, 14);
        java.awt.Color textDark = new java.awt.Color(51, 51, 51);

        // 1. Kolom No (Kecil di kiri)
        javax.swing.JLabel lblNo = new javax.swing.JLabel(String.valueOf(nomor));
        lblNo.setFont(fontIsi);
        lblNo.setForeground(textDark);
        lblNo.setBounds(20, 15, 30, 20);
        panel.add(lblNo);

        // 2. Kolom Nama Peminjam (Agak lebar)
        javax.swing.JLabel lblNama = new javax.swing.JLabel(log.getNamaPeminjam());
        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // Bold untuk nama
        lblNama.setForeground(textDark);
        lblNama.setBounds(60, 15, 180, 20);
        panel.add(lblNama);

        // 3. Kolom Aktivitas (Paling lebar & Berwarna)
        String aktivitas = log.getAktivitas();
        javax.swing.JLabel lblAkt = new javax.swing.JLabel(aktivitas);
        lblAkt.setFont(fontIsi);
        
        if (aktivitas.toLowerCase().contains("gagal") || aktivitas.toLowerCase().contains("ditolak")) {
            lblAkt.setForeground(java.awt.Color.RED);
        } else if (aktivitas.toLowerCase().contains("mengembalikan")) {
            lblAkt.setForeground(new java.awt.Color(0, 102, 204));
        } else if (aktivitas.toLowerCase().contains("sedang")) {
            lblAkt.setForeground(new java.awt.Color(0, 153, 0));
        } else {
            lblAkt.setForeground(textDark); 
        }
        
        lblAkt.setBounds(250, 15, 350, 20);
        panel.add(lblAkt);

        // 4. Kolom Waktu
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd MMM yyyy");
        String tglStr = (log.getTanggal() != null) ? sdf.format(log.getTanggal()) : "-";
        
        javax.swing.JLabel lblWaktu = new javax.swing.JLabel(tglStr);
        lblWaktu.setFont(fontIsi);
        lblWaktu.setForeground(java.awt.Color.GRAY);
        lblWaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWaktu.setBounds(600, 15, 120, 20); 
        panel.add(lblWaktu);

        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelLogContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addbarang = new javax.swing.JButton();
        editbarang = new javax.swing.JButton();
        hapusbarang = new javax.swing.JButton();
        logpeminjaman = new javax.swing.JButton();
        reqpeminjaman = new javax.swing.JButton();
        reqpengembalian = new javax.swing.JButton();
        addbarang1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 204, 0));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Log Peminjaman");
        jLabel2.setPreferredSize(new java.awt.Dimension(204, 50));
        jPanel4.add(jLabel2, new java.awt.GridBagConstraints());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelLogContainer.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout panelLogContainerLayout = new javax.swing.GroupLayout(panelLogContainer);
        panelLogContainer.setLayout(panelLogContainerLayout);
        panelLogContainerLayout.setHorizontalGroup(
            panelLogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        panelLogContainerLayout.setVerticalGroup(
            panelLogContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelLogContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jScrollPane1, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        addbarang.setBackground(new java.awt.Color(60, 63, 65));
        addbarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addbarang.setForeground(new java.awt.Color(255, 255, 255));
        addbarang.setText("Tambah Barang");
        addbarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addbarang.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbarangActionPerformed(evt);
            }
        });

        editbarang.setBackground(new java.awt.Color(60, 63, 65));
        editbarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editbarang.setForeground(new java.awt.Color(255, 255, 255));
        editbarang.setText("Edit Barang");
        editbarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editbarang.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        editbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbarangActionPerformed(evt);
            }
        });

        hapusbarang.setBackground(new java.awt.Color(60, 63, 65));
        hapusbarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapusbarang.setForeground(new java.awt.Color(255, 255, 255));
        hapusbarang.setText("Hapus Barang");
        hapusbarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hapusbarang.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        hapusbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbarangActionPerformed(evt);
            }
        });

        logpeminjaman.setBackground(new java.awt.Color(0, 204, 0));
        logpeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logpeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        logpeminjaman.setText("Log Peminjaman");
        logpeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logpeminjaman.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logpeminjamanActionPerformed(evt);
            }
        });

        reqpeminjaman.setBackground(new java.awt.Color(60, 63, 65));
        reqpeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reqpeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        reqpeminjaman.setText("Request Peminjaman");
        reqpeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reqpeminjaman.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        reqpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqpeminjamanActionPerformed(evt);
            }
        });

        reqpengembalian.setBackground(new java.awt.Color(60, 63, 65));
        reqpengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reqpengembalian.setForeground(new java.awt.Color(255, 255, 255));
        reqpengembalian.setText("Request Pengembalian");
        reqpengembalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reqpengembalian.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        reqpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqpengembalianActionPerformed(evt);
            }
        });

        addbarang1.setBackground(new java.awt.Color(60, 63, 65));
        addbarang1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addbarang1.setForeground(new java.awt.Color(255, 255, 255));
        addbarang1.setText("Dashboard");
        addbarang1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addbarang1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addbarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbarang1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logpeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reqpeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reqpengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addbarang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(addbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reqpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reqpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SiUkm - Sistem Inventaris UKM");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbarangActionPerformed
        new tambahbarang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addbarangActionPerformed

    private void editbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbarangActionPerformed
        new editbarang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editbarangActionPerformed

    private void hapusbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbarangActionPerformed
        new hapusbarang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hapusbarangActionPerformed

    private void logpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logpeminjamanActionPerformed
        new LogPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logpeminjamanActionPerformed

    private void reqpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqpeminjamanActionPerformed
        new RequestPeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reqpeminjamanActionPerformed

    private void reqpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqpengembalianActionPerformed
        new RequestPengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reqpengembalianActionPerformed

    private void addbarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbarang1ActionPerformed
        new DashboardAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addbarang1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Logout
        Utils.UserSession.getInstance().clearSession();
        javax.swing.JOptionPane.showMessageDialog(this, "Berhasil logout!");
        new Register.LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogPeminjaman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbarang;
    private javax.swing.JButton addbarang1;
    private javax.swing.JButton editbarang;
    private javax.swing.JButton hapusbarang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logpeminjaman;
    private javax.swing.JPanel panelLogContainer;
    private javax.swing.JButton reqpeminjaman;
    private javax.swing.JButton reqpengembalian;
    // End of variables declaration//GEN-END:variables
}
