/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Peminjam;

import Model.RequestData;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author aldriknoel
 */
public class DetailRiwayat extends javax.swing.JDialog {
    public DetailRiwayat(java.awt.Frame parent, RequestData data, boolean modal) {
        super(parent, modal);
        initCustomComponents(data); 
        setLocationRelativeTo(parent); 
    }

    private void initCustomComponents(RequestData data) {
        setTitle("Detail Peminjaman");
        setSize(500, 600); 
        setLayout(null);
        getContentPane().setBackground(Color.WHITE);

        JPanel headerPanel = new JPanel();
        headerPanel.setBounds(0, 0, 500, 60);
        headerPanel.setBackground(new Color(0, 204, 0));
        headerPanel.setLayout(null);
        add(headerPanel);

        JLabel lblTitle = new JLabel("Detail Transaksi");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setBounds(20, 15, 300, 30);
        headerPanel.add(lblTitle);

        int yStart = 80;
        int gap = 35;
        Font labelFont = new Font("Segoe UI", Font.BOLD, 14);
        Font valueFont = new Font("Segoe UI", Font.PLAIN, 14);

        addDetailRow("Nama Barang", data.getNamaBarang(), yStart, labelFont, valueFont);
        
        addDetailRow("Jumlah Pinjam", data.getJumlah() + " Unit", yStart + gap, labelFont, valueFont);

        addDetailRow("Tanggal Pinjam", String.valueOf(data.getTanggalPinjam()), yStart + gap * 2, labelFont, valueFont);
        addDetailRow("Jatuh Tempo", String.valueOf(data.getTanggalKembali()), yStart + gap * 3, labelFont, valueFont);
        addDetailRow("Status", data.getStatus().toUpperCase(), yStart + gap * 4, labelFont, valueFont);

        JLabel lblKet = new JLabel("Keterangan :");
        lblKet.setFont(labelFont);
        lblKet.setBounds(30, yStart + gap * 5, 120, 20);
        add(lblKet);

        JTextArea txtKet = new JTextArea(data.getKeterangan());
        txtKet.setFont(valueFont);
        txtKet.setLineWrap(true);
        txtKet.setWrapStyleWord(true);
        txtKet.setEditable(false);
        txtKet.setBackground(new Color(245, 245, 245));
        txtKet.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        txtKet.setBounds(30, yStart + gap * 5 + 25, 420, 80); 
        add(txtKet);

        int yDenda = yStart + gap * 8 + 10;
        JLabel lblDendaJudul = new JLabel("Denda :");
        lblDendaJudul.setFont(labelFont);
        lblDendaJudul.setBounds(30, yDenda, 100, 20);
        add(lblDendaJudul);

        JLabel lblDendaNilai = new JLabel("-");
        lblDendaNilai.setFont(valueFont);
        java.util.Date today = new java.util.Date();
        if ("disetujui".equalsIgnoreCase(data.getStatus()) && data.getTanggalKembali() != null && today.after(data.getTanggalKembali())) {
             lblDendaNilai.setText("Rp 50.000 (Terlambat)");
             lblDendaNilai.setForeground(Color.RED);
        }
        lblDendaNilai.setBounds(150, yDenda, 300, 20);
        add(lblDendaNilai);

        JButton btnClose = new JButton("Tutup");
        btnClose.setBounds(190, yDenda + 50, 100, 35);
        btnClose.setBackground(new Color(60, 63, 65));
        btnClose.setForeground(Color.WHITE);
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(e -> dispose());
        add(btnClose);
    }

    private void addDetailRow(String label, String value, int y, Font fLabel, Font fValue) {
        JLabel lbl = new JLabel(label + " :");
        lbl.setFont(fLabel);
        lbl.setBounds(30, y, 150, 20); 
        add(lbl);

        JLabel val = new JLabel(value);
        val.setFont(fValue);
        
        val.setBounds(190, y, 250, 20); 

        if (label.equals("Status")) {
            if (value.equalsIgnoreCase("DISETUJUI")) val.setForeground(new Color(0, 153, 0));
            else if (value.equalsIgnoreCase("DITOLAK")) val.setForeground(Color.RED);
            else if (value.equalsIgnoreCase("PROSES")) val.setForeground(Color.ORANGE);
        }
        
        add(val);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DetailRiwayat dialog = new DetailRiwayat(new javax.swing.JFrame(), new RequestData(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
